version: '3.9'

volumes:
   geoserver-cluster-data:

services:
   master:
      image: kartoza/geoserver:2.19.2
      volumes:
         - geoserver-cluster-data:/opt/geoserver/data_dir
      ports:
        - "8081:8080"
      environment:
        - BROKER_URL=tcp://0.0.0.0:61661
        - READONLY=disabled
        - CLUSTER_DURABILITY=false
        - CLUSTERING=True
        - TOGGLE_MASTER=true
        - TOGGLE_SLAVE=true
      restart: on-failure
      healthcheck:
        test: curl --fail -s http://localhost:8080/ || exit 1
        interval: 1m30s
        timeout: 10s
        retries: 3
   node:
      image: kartoza/geoserver:2.19.2
      volumes:
         - geoserver-cluster-data:/opt/geoserver/data_dir
      ports:
        - "8082:8080"
      environment:
        - BROKER_URL=tcp://master:61661
        - READONLY=disabled
        - CLUSTER_DURABILITY=false
        - CLUSTERING=True
        - TOGGLE_MASTER=true
        - TOGGLE_SLAVE=true
        - EMBEDDED_BROKER=disabled
      restart: on-failure
      depends_on:
        master:
          condition: service_healthy
      healthcheck:
        test: curl --fail -s http://localhost:8080/ || exit 1
        interval: 1m30s
        timeout: 10s
        retries: 3

   

