sudo: required

language: python

services:
  - docker

python:
  - '3.7'

env:
  - SCENARIO=restore
  #- SCENARIO=s3

before_script:
  - ./build-test.sh

script:
  - pushd scenario_tests/${SCENARIO}
  - ./test.sh
  - popd
